# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  # vmImage: 'windows-latest'
  vmImage: 'windows-2022' # C Sharp 10 experimental features used

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.x'
  buildPlatform: 'Any CPU'
  releaseVersion: "1.0.0.$(build.buildNumber)"

steps:

- task: UseDotNet@2
  displayName: 'Set .NET Version'
  inputs:
    version: $(dotNetVersion)
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Restore NuGet Dependancies
  inputs:
    command: restore
    arguments: "**/*.csproj"

- task: CmdLine@2
  displayName: Show Build.SourcesDirectory Content
  inputs:
    script: 'tree $(Build.SourcesDirectory) /f' 

- task: DotNetCoreCLI@2
  displayName: 'Build Repository Projects'
  inputs:
    projects: '**/*.csproj'
    arguments: '/p:Version=$(releaseVersion)'

- task: VSTest@2
  displayName: Run Unit Tests
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Package Project'
  inputs:
    command: pack
    nobuild: true
    versioningScheme: byEnvVar
    versionEnvVar: releaseVersion

- task: DotNetCoreCLI@2
  displayName: 'Push Project to Article Feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'e6d3f8af-b2d9-4284-af11-9b3f8889d7f1/bafc94e5-8e35-4df1-8b31-c4c3d270f5c8'

- task: CmdLine@2
  displayName: Show Publish Content
  inputs:
    script: 'tree $(Build.ArtifactStagingDirectory) /f' 
